os: linux
language: python
python: 2.7

before_script:
  - sudo wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig
  - sudo cp wigToBigWig /usr/local/bin
  - sudo ls /usr/local/bin
  - export PATH=/usr/local/bin:$PATH

script:
  - python gap2bigwig.py example.fna
  - python GCcontent2bigwig.py example.fna
