os: linux
language: python
python: 2.7


before_script:
  - wget P /usr/local/bin http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig

script:
  - python gap2bigwig.py example.fna
  - python GCcontent2bigwig.py example.fna
