os: linux
language: python
python: 2.7

before_script:
  - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig
  - sudo cp wigToBigWig /usr/local/bin
  - echo $PATH
  - sudo ls /usr/local/bin


script:
  - python gap2bigwig.py example.fna
  - python GCcontent2bigwig.py example.fna
